# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('post_image_url', models.CharField(default='', max_length=400)),
                ('post_image', models.ImageField(upload_to='static')),
            ],
        ),
    ]
