# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image_url',
            field=models.CharField(default='<empty>', max_length=400),
        ),
    ]
